// src/data/posts.js
export const posts = [
    {
      id: 1,
      title: "Business strategy for a brand of vintage bags",
      category: "Brand strategy",
      time: "9 hours ago",
      description: "Pharetra in morbi quis is massa maecenas arcu vulputate pulvinar elit non nullage a, duis tortor mi massa ipsum in eu eu eget libero pulvinar elit vulputate...",
      link: "blog-single-v1.html",
      image: "/assets/images/contactusimage.png",
    },
    {
      id: 2,
      title: "Top books for inspiration",
      category: "Books",
      time: "12 hours ago",
      description: "Vulputate auctor lacus imperdiet facilisi tristique nisl pulvinar porta diam duis odio",
      link: "blog-single-v2.html",
      image: "/assets/images/contactusimage.png",
    },
    {
        id: 2,
        title: "Top books for inspiration",
        category: "Books",
        time: "12 hours ago",
        description: "Vulputate auctor lacus imperdiet facilisi tristique nisl pulvinar porta diam duis odio",
        link: "blog-single-v2.html",
        image: "/assets/images/contactusimage.png",
      }, {
        id: 2,
        title: "Top books for inspiration",
        category: "Books",
        time: "12 hours ago",
        description: "Vulputate auctor lacus imperdiet facilisi tristique nisl pulvinar porta diam duis odio",
        link: "blog-single-v2.html",
        image: "/assets/images/contactusimage.png",
      }, {
        id: 2,
        title: "Top books for inspiration",
        category: "Books",
        time: "12 hours ago",
        description: "Vulputate auctor lacus imperdiet facilisi tristique nisl pulvinar porta diam duis odio",
        link: "blog-single-v2.html",
        image: "/assets/images/contactusimage.png",
      }, {
        id: 2,
        title: "Top books for inspiration",
        category: "Books",
        time: "12 hours ago",
        description: "Vulputate auctor lacus imperdiet facilisi tristique nisl pulvinar porta diam duis odio",
        link: "blog-single-v2.html",
        image: "/assets/images/contactusimage.png",
      }, {
        id: 2,
        title: "Top books for inspiration",
        category: "Books",
        time: "12 hours ago",
        description: "Vulputate auctor lacus imperdiet facilisi tristique nisl pulvinar porta diam duis odio",
        link: "blog-single-v2.html",
        image: "/assets/images/contactusimage.png",
      }, {
        id: 2,
        title: "Top books for inspiration",
        category: "Books",
        time: "12 hours ago",
        description: "Vulputate auctor lacus imperdiet facilisi tristique nisl pulvinar porta diam duis odio",
        link: "blog-single-v2.html",
        image: "/assets/images/contactusimage.png",
      }, {
        id: 2,
        title: "Top books for inspiration",
        category: "Books",
        time: "12 hours ago",
        description: "Vulputate auctor lacus imperdiet facilisi tristique nisl pulvinar porta diam duis odio",
        link: "blog-single-v2.html",
        image: "/assets/images/contactusimage.png",
      }, {
        id: 2,
        title: "Top books for inspiration",
        category: "Books",
        time: "12 hours ago",
        description: "Vulputate auctor lacus imperdiet facilisi tristique nisl pulvinar porta diam duis odio",
        link: "blog-single-v2.html",
        image: "/assets/images/contactusimage.png",
      }, {
        id: 2,
        title: "Top books for inspiration",
        category: "Books",
        time: "12 hours ago",
        description: "Vulputate auctor lacus imperdiet facilisi tristique nisl pulvinar porta diam duis odio",
        link: "blog-single-v2.html",
        image: "/assets/images/contactusimage.png",
      }, {
        id: 2,
        title: "Top books for inspiration",
        category: "Books",
        time: "12 hours ago",
        description: "Vulputate auctor lacus imperdiet facilisi tristique nisl pulvinar porta diam duis odio",
        link: "blog-single-v2.html",
        image: "/assets/images/contactusimage.png",
      }, {
        id: 2,
        title: "Top books for inspiration",
        category: "Books",
        time: "12 hours ago",
        description: "Vulputate auctor lacus imperdiet facilisi tristique nisl pulvinar porta diam duis odio",
        link: "blog-single-v2.html",
        image: "/assets/images/contactusimage.png",
      }, {
        id: 2,
        title: "Top books for inspiration",
        category: "Books",
        time: "12 hours ago",
        description: "Vulputate auctor lacus imperdiet facilisi tristique nisl pulvinar porta diam duis odio",
        link: "blog-single-v2.html",
        image: "/assets/images/contactusimage.png",
      }, {
        id: 2,
        title: "Top books for inspiration",
        category: "Books",
        time: "12 hours ago",
        description: "Vulputate auctor lacus imperdiet facilisi tristique nisl pulvinar porta diam duis odio",
        link: "blog-single-v2.html",
        image: "/assets/images/contactusimage.png",
      }, {
        id: 2,
        title: "Top books for inspiration",
        category: "Books",
        time: "12 hours ago",
        description: "Vulputate auctor lacus imperdiet facilisi tristique nisl pulvinar porta diam duis odio",
        link: "blog-single-v2.html",
        image: "/assets/images/contactusimage.png",
      }, {
        id: 2,
        title: "Top books for inspiration",
        category: "Books",
        time: "12 hours ago",
        description: "Vulputate auctor lacus imperdiet facilisi tristique nisl pulvinar porta diam duis odio",
        link: "blog-single-v2.html",
        image: "/assets/images/contactusimage.png",
      }, {
        id: 2,
        title: "Top books for inspiration",
        category: "Books",
        time: "12 hours ago",
        description: "Vulputate auctor lacus imperdiet facilisi tristique nisl pulvinar porta diam duis odio",
        link: "blog-single-v2.html",
        image: "/assets/images/contactusimage.png",
      }, {
        id: 2,
        title: "Top books for inspiration",
        category: "Books",
        time: "12 hours ago",
        description: "Vulputate auctor lacus imperdiet facilisi tristique nisl pulvinar porta diam duis odio",
        link: "blog-single-v2.html",
        image: "/assets/images/contactusimage.png",
      }, {
        id: 2,
        title: "Top books for inspiration",
        category: "Books",
        time: "12 hours ago",
        description: "Vulputate auctor lacus imperdiet facilisi tristique nisl pulvinar porta diam duis odio",
        link: "blog-single-v2.html",
        image: "/assets/images/contactusimage.png",
      }, {
        id: 2,
        title: "Top books for inspiration",
        category: "Books",
        time: "12 hours ago",
        description: "Vulputate auctor lacus imperdiet facilisi tristique nisl pulvinar porta diam duis odio",
        link: "blog-single-v2.html",
        image: "/assets/images/contactusimage.png",
      }, {
        id: 2,
        title: "Top books for inspiration",
        category: "Books",
        time: "12 hours ago",
        description: "Vulputate auctor lacus imperdiet facilisi tristique nisl pulvinar porta diam duis odio",
        link: "blog-single-v2.html",
        image: "/assets/images/contactusimage.png",
      }, {
        id: 2,
        title: "Top books for inspiration",
        category: "Books",
        time: "12 hours ago",
        description: "Vulputate auctor lacus imperdiet facilisi tristique nisl pulvinar porta diam duis odio",
        link: "blog-single-v2.html",
        image: "/assets/images/contactusimage.png",
      },
    // Add more posts as needed
  ];
  